------------------------------------------------------------
/usr/bin/pip run on Tue Sep 23 14:53:57 2014
Uninstalling tornado:

  /usr/local/lib/python2.7/dist-packages/tornado-4.0.2.egg-info

  Removing file or directory /usr/local/lib/python2.7/dist-packages/tornado-4.0.2.egg-info
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 41, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 862, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 486, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1431, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 263, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/tornado-4.0.2.egg-info'

